#ifndef INCLUDES
#define INCLUDES

#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h> 
#include <signal.h>
#include <semaphore.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <time.h>
#include <errno.h>
#include <string>
#include <iostream>
#include <vector>
#include <queue>
#include <map>
#include <sys/types.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/shm.h>
#include <sys/ipc.h> 
#include <sys/time.h>
#include "LogBook.h"
#include "Packets.h"
#include "StatisticsDataPlane.h"
#include <ifaddrs.h>
#include <thread> 
#include <memory> 
#include <utility>
#include <chrono>
#include <functional>
#include <atomic>
#include <future>
#include <mutex> 
#include <numeric>
#include <algorithm>
#include <mutex>
#include <limits>
#include <cinttypes>
#include <chrono>
#include <ctime>
#include <iostream>
#include <iomanip>

#endif
